---
# tasks file for tom7role
- name: install tomcat7
  apt:
    name: tomcat7
    state: latest

- name: copy config file into all nodes
  template:
     src: templates/javaconfig.j2
     dest: /etc/default/tomcat
  notify: restarttomcat

- name: install additional packages
  apt:
    name: "{{item}}"
    state: present
  loop:
    - tomcat7-docs
    - tomcat7-admin
    - tomcat7-examples

- name: copy usermanagement files into nodes
  template:
    src: templates/usermanagement.j2
    dest: /etc/tomcat7/tomcat-users.xml
  notify: restarttomcat

- name: deploy javaapp into nodes
  get_url:
    url: https://maha1234.s3-us-west-2.amazonaws.com/mahaLogin.war
    dest: /var/lib/tomcat7/webapps/mahaLogin.war
    force_basic_auth: yes
